development:
  adapter: postgresql
  encoding: utf8
  database: smaple_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: smaple_test
  pool: 5
  username: 
  password: 