development:
  adapter: postgresql
  encoding: utf8
  database: sample_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: sample_test
  pool: 5
  username: 
  password: 